version: "3.9"
services:
  db:
    image: postgres:11-bullseye
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=notification_api
      - POSTGRES_USER=notify
      - POSTGRES_PASSWORD=notify
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 1s
      retries: 3

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6380:6379"

  notify-api:
    image: notifications-api
    container_name: notify-api
    volumes:
      - ../notifications-api:/home/vcap/app
    build:
      context: ../notifications-api
      dockerfile: docker/Dockerfile
    ports:
      - "6011:6011"
    command: ["api-local"]
    env_file:
      - notify-api.env
    environment: &api-environment
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SESSION_TOKEN
      - AWS_CREDENTIAL_EXPIRATION
      - AWS_REGION
      - AWS_DEFAULT_REGION
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      notify-api-db-migration:
        condition: service_started

  notify-api-db-migration:
    image: notifications-api
    container_name: db-migration
    volumes:
      - ../notifications-api:/home/vcap/app
    command: ["migration"]
    env_file:
      - notify-api.env
    environment:
      *api-environment
    depends_on:
      db:
        condition: service_healthy

  notify-api-celery:
    image: notifications-api
    container_name: notify-api-celery
    volumes:
      - ../notifications-api:/home/vcap/app
    command: ["worker"]
    env_file:
      - notify-api.env
    environment:
      *api-environment
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
 
  notify-api-celery-beat:
    image: notifications-api
    container_name: notify-api-celery-beat
    volumes:
      - ../notifications-api:/home/vcap/app
    command: ["celery-beat"]
    env_file:
      - notify-api.env
    environment:
      *api-environment
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
 
  notify-admin:
    image: notifications-admin
    container_name: notify-admin
    volumes:
      - ../notifications-admin:/home/vcap/app
    build:
      context: ../notifications-admin
      dockerfile: docker/Dockerfile
      args:
        - NOTIFY_ENVIRONMENT=development
    ports:
      - "6012:6012"
    command: ["flask", "run", "--port", "6012", "--host", "0.0.0.0"]
    env_file:
      - notify-admin.env
    depends_on:
      notify-api:
        condition: service_started
